nodeLinker: node-modules

packageExtensions:
  "@nocobase/client@*":
    dependencies:
      "deepmerge": "*"
      "d3-format": "*"
      "history": "*"
      "nanoid": "*"
      "qs": "*"
      "rc-motion": "*"
      "rc-util": "*"
      "react-imported-component": "*"
      "react-router": "*"
      "react-router-dom": "*"
      "react-transition-group": "*"
      "react-use": "*"
      "styled-components": "*"
      "uuid": "*"
      "web-vitals": "*"

  "@nocobase/utils@*":
    dependencies:
      "@formily/json-schema": "*"
      "lodash": "*"
      "lodash-es": "*"

  "antd@*":
    dependencies:
      "@ant-design/icons": "*"
      "@ant-design/react-slick": "*"
      "classnames": "*"
      "rc-field-form": "*"
      "rc-motion": "*"
      "rc-util": "*"
      "react-slick": "*"

  "@formily/react@*":
    dependencies:
      "@formily/core": "*"
      "@formily/json-schema": "*"
      "@formily/path": "*"
      "@formily/shared": "*"
      "react": "*"
      "react-dom": "*"

  "react@*":
    peerDependencies:
      "react-dom": "*"

  "react-dom@*":
    peerDependencies:
      "react": "*" 